
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = ""
  port = 465
  to = ""
  user = ""

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "192.168.1.2:3306"
    name = "gblog"
    pass = "520530"
    user = "root"

  [mysql.write]
    addr = "192.168.1.2:3306"
    name = "gblog"
    pass = "520530"
    user = "root"

[redis]
  addr = "192.168.1.2:6379"
  db = "4"
  maxretries = 3
  minidleconns = 5
  pass = "520530"
  poolsize = 10
